### ISSUE TITLE
Risolvo i tuoi problemi

### ISSUE THREAD

**Issue by SimoneMadd** [fromVeeko/zooDatabase#1]
Ciao sono Simone Maddiona, studente al terzo anno di STM 
Ho gia l'esercizio completo da passarti, appena fatto per altre vostre compagne di corso.

Ti dico, ti sei complicato un po la vita con tutto quel codice, ma approcciare php all'inizio è tosta, quindi tutto normale non preoccuparti!

Per il fatto del db, probabilmente non gli hai settato che puo ricevere anche un dato NULL, quindi una variabile vuota ed è per quello che quando lo fai dal form non te lo inserisce!
Poi ti consiglio di usare post non get. Detto questo dopo ti mando tutto

**Comment by fromVeeko** [comment]
Grazie mille simone! Era più lineare di questo ti giuro ahah. Solo due giorni a rimaneggiarlo lo hanno portato ad essere la chimera che è diventato.

Grazie per la dritta di usare il metodo post; stavo iniziando a pensarci e mi hai dato il la definitivo. 
Su questa cosa del dato NULL ho una domanda: cercando sul webbe ho visto spesso (e usato) VAR_TYPE NOT NULL, e ho quindi supposto che di default accettasse NULL (sbagliando a quanto pare)

Grazie ancora, commento utilissimo

**Comment by SimoneMadd** [comment]
E' proprio il VAR_TYPE NOT NULL che ti frega, perche ti dice proprio **NOT NULL**, quindi **_"AHO VEDI CHE NON ACCETTO I NULL"_**
